system:
  host: localhost
  port: 5001
db:
  host: localhost
  port: 3306
  dbName: turingcup
  charset: utf8mb4
  userName: turing
  password: 123456789
skywalking:
  host: localhost
  port: 11800
ses:
  id: AKIDHWkRAkG3WwLHC5vmbTQRI2Zt0wfDbppc
  key: gAcvmV1INFuLZcT7YovqY3MSL1VmqgN

