system:
  host: 0.0.0.0
  port: 5001
db:
  host: db
  port: 3306
  dbName: turingcup
  charset: utf8mb4
  userName: turing
  password: Lird2002@@
skywalking:
  host: skywalking-oap
  port: 11800
ses:
  id: AKIDHWkRAkG3WwLHC5vmbTQRI2Zt0wfDbppc
  key: gAcvmV1INFuLZcT7YovqY3MSL1VmqgNt
redis:
  host: redis
  port: 6379
  password:
